import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
export async function generateTokens() {
  const tokens = JSON.parse(await readFile(new URL('../src/prototype/tokens.json', import.meta.url), 'utf8'));
  const css = ['/* Generated by npm run tokens. Edit tokens.json. */', ':root {', ...Object.entries(tokens.primitive).map(([key,value]) => `  --p-${key}: ${value};`), ...Object.entries(tokens.shared).map(([key,value]) => `  --${key}: ${value};`), '}'];
  for (const [theme, values] of Object.entries(tokens.themes)) css.push(`${theme === 'light' ? ':root, ' : ''}[data-theme="${theme}"] {`, ...Object.entries(values).map(([key,value]) => `  --${key}: ${value.startsWith('@') ? `var(--p-${value.slice(1)})` : value};`), '}');
  return css.join('\n') + '\n';
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await writeFile(new URL('../src/prototype/tokens.css', import.meta.url), await generateTokens());
