import { TYPES, ACTORS, SEEDS } from './catalog.mjs';
import { catalog, resource, isInstalled } from './state.mjs';
import { esc, icon, badge, button, card, empty, field, safeLink, typeClass } from './components.mjs';

export function shell(state, ui, content) {
  const nav = [['discover','grid','发现资源'],['library','book','我的资源'],['publications','upload','我的发布'],['updates','clock','更新与恢复'],['sources','link','资源来源'],['task','chat','任务草稿']];
  return `<a class="skip-link" href="#main-content">跳到主要内容</a><div class="prototype-bar"><span><span class="status-dot"></span>交互原型 · 本机保存，不会真实安装、公开发布或调用模型</span><label>体验身份 <select id="actor" aria-label="体验身份">${Object.entries(ACTORS).map(([key,name])=>`<option value="${key}" ${state.actor===key?'selected':''}>${name}</option>`).join('')}</select></label></div><div class="app-shell"><aside class="sidebar ${ui.menu?'open':''}"><a class="brand" href="#/discover"><span class="brand-mark">${icon('box')}</span><strong>DSH<span>COMMUNITY</span></strong></a><div class="workspace-label">你的能力工作台</div><nav aria-label="主导航">${nav.map(([id,glyph,label])=>`<a href="#/${id}" class="nav-link ${ui.route===id?'active':''}" ${ui.route===id?'aria-current="page"':''}>${icon(glyph)}<span>${label}</span>${id==='library'&&state.saved[state.actor].length?`<span class="nav-count">${state.saved[state.actor].length}</span>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="community-note">${icon('leaf')}<strong>好工具，来自每一份分享。</strong><p>让一个人的好方法，成为更多人的起点。</p><a href="#/share">分享你的资源 ${icon('arrow')}</a></div><div class="sidebar-footer"><span class="avatar">${state.actor==='reader'?'用':'创'}</span><span>${ACTORS[state.actor]}<small>本机体验身份</small></span></div></div></aside><div class="main-wrap"><header class="topbar">${button(icon('menu'),'data-action="menu" aria-label="展开导航"','ghost menu-button')}<div class="breadcrumb">社区资源 <span>/</span> <strong>${({discover:'发现',library:'我的资源',publications:'我的发布',updates:'更新与恢复',sources:'来源',task:'任务草稿',share:'分享资源',resource:'资源详情'})[ui.route]||'发现'}</strong></div><div class="top-actions">${button(icon('sun'),'data-action="theme" aria-label="切换深浅主题"','ghost icon-button')}<a class="button primary" href="#/share">${icon('plus')} 分享资源</a></div></header><main id="main-content" tabindex="-1">${content}</main><footer class="page-footer"><span>DSH 社区资源 · 让能力持续生长</span><span>来源样本与本机投稿分别标注</span></footer></div></div>`;
}

export function discoverView(state, ui) {
  const all = catalog(state);
  const items = all.filter(item=>(ui.filter==='全部'||item.type===ui.filter)&&`${item.title} ${item.summary} ${item.author} ${item.type} ${item.tag}`.toLowerCase().includes(ui.query.toLowerCase()));
  const featured = SEEDS[0];
  return `<section class="page-heading"><div class="eyebrow">DISCOVER & CREATE</div><h1>发现社区的好工具<span class="heading-dot">.</span></h1><p>找到顺手的能力，让你的下一次任务更简单。</p></section><div class="discovery-hero"><a class="feature-card" href="#/resource/weekly-prompt"><div class="feature-copy"><span class="feature-kicker">${icon('text')} 从一个好提示词开始</span><h2>写好一次，<br>下次直接用。</h2><p>把零散记录整理成清楚的周报，<br>先预览，再交给你的 Agent。</p><span class="feature-cta">试用周报模板 ${icon('arrow')}</span></div><div class="paper-preview" aria-hidden="true"><div class="paper-top"><span>WEEKLY NOTES</span>${icon('text')}</div><strong>本周的进展，一目了然。</strong><div class="paper-section">01 <span>本周进展</span></div><div class="paper-line"></div><div class="paper-line short"></div><div class="paper-section">02 <span>问题与待确认</span></div><div class="paper-line"></div><div class="paper-section">03 <span>下周计划</span></div><div class="paper-line short"></div><span class="paper-label">Prompt · 本项目自编样本</span></div></a><aside class="share-feature"><span class="share-symbol">${icon('spark')}</span><span class="eyebrow">BUILT TOGETHER</span><h2>你的好方法，<br>值得被更多人看见。</h2><p>分享提示词、工具或技能，<br>让社区多一种可能。</p><a href="#/share">开始分享 ${icon('arrow')}</a></aside></div><section class="catalog-section" aria-labelledby="catalog-title"><div class="section-head"><h2 id="catalog-title">探索资源 <span>${all.length}</span></h2><label class="search-field">${icon('search')}<input id="search" aria-label="搜索资源" value="${esc(ui.query)}" placeholder="搜索用途、名称或作者"><kbd>/</kbd></label></div><div class="filter-row" role="group" aria-label="资源类型">${['全部',...TYPES].map(type=>button(esc(type),`data-action="filter" data-type="${esc(type)}" aria-pressed="${ui.filter===type}"`,ui.filter===type?'filter selected':'filter')).join('')}<span class="results-note">${ui.query||ui.filter!=='全部'?`${items.length} 个结果`:'从用途出发，找到合适的能力'}</span></div>${items.length?`<div class="resource-grid">${items.map(item=>card(item,state)).join('')}</div>`:empty('还没有找到匹配的资源','试试其他关键词，或切换资源类型。',button('清除筛选','data-action="clearFilters"'))}<p class="catalog-note">${icon('check')}外部资源已核查来源说明，DSH 适配尚待实测；本机投稿仅用于体验。</p></section>`;
}

export function detailView(state, ui) {
  const item = ui.copy ? state.saved[state.actor].find(entry=>entry.id===ui.id) || resource(state,ui.id) : resource(state,ui.id);
  if (!item) return empty('资源暂不可用','它可能已撤回，或当前身份没有保存副本。','<a class="button primary" href="#/discover">返回发现</a>');
  const saved = state.saved[state.actor].some(entry=>entry.id===item.id);
  const installed = isInstalled(state,item.id);
  const feedback = state.feedback[item.id]||[];
  return `<a class="back-link" href="#/discover">${icon('back')} 返回发现</a><div class="detail-heading"><span class="resource-icon large ${typeClass(item.type)}">${icon(item.icon)}</span><div>${badge(item.type)}<h1>${esc(item.title)}</h1><p>${esc(item.author)} <span class="dot-separator">·</span> ${esc(item.source)}</p></div></div><div class="detail-layout"><div class="detail-main"><p class="detail-summary">${esc(item.summary)}</p><div class="detail-tabs" role="group" aria-label="详情内容">${[['overview','概览'],['versions','版本记录'],['feedback',`反馈 ${feedback.length}`]].map(([id,label])=>button(esc(label),`data-action="detailTab" data-tab="${id}" aria-pressed="${ui.detailTab===id}"`,ui.detailTab===id?'tab selected':'tab')).join('')}</div>${ui.detailTab==='versions'?`<h2>版本记录</h2>${(item.versions||[{version:item.version,summary:'来源核查样本，尚未验证安装与运行。'}]).slice().reverse().map(version=>`<div class="version-row"><strong>${esc(version.version)}</strong><p>${esc(version.summary)}</p></div>`).join('')}`:ui.detailTab==='feedback'?`<div class="section-head"><h2>让资源变得更好</h2>${button('写反馈',`data-action="feedback" data-id="${esc(item.id)}"`)}</div>${feedback.length?feedback.map(entry=>`<div class="feedback-item"><strong>${ACTORS[entry.actor]||'体验用户'}</strong><p>${esc(entry.text)}</p></div>`).join(''):empty('还没有反馈','试用后，分享具体的建议或遇到的问题。')}`:`<h2>${item.type==='Prompt'?'提示词内容':'这份资源能做什么'}</h2><pre class="content-preview">${esc(item.body||'作者尚未提供详细说明。')}</pre><h2>开始前，了解这些</h2><div class="requirement-note">${icon('check')}<p>${esc(item.requirements)}</p></div>${item.parent?`<a class="related-resource" href="#/resource/${item.parent}">${icon('box')}<span>来自规划模式插件<small>共用安装与版本，不重复添加</small></span>${icon('arrow')}</a>`:item.id==='plan-plugin'?`<a class="related-resource" href="#/resource/plan-command">${icon('slash')}<span>包含 /plan 命令<small>查看命令用法和使用入口</small></span>${icon('arrow')}</a>`:''}`}</div><aside class="action-panel"><div class="action-state">${badge(item.type==='Prompt'?'可填写预览':installed?'已添加 · 演示':'来源已核查',installed?'success':'')}<p>${item.type==='Prompt'?'填写你的内容，预览后放入任务。':'真实安装与调用尚未接入，可体验操作流程。'}</p></div>${button(item.type==='Prompt'?'使用提示词':installed?(item.type==='MCP'?'模拟连接设置':'体验使用流程'):(item.type==='MCP'?'模拟连接':'模拟添加'),`data-action="${item.type==='Prompt'?'usePrompt':'install'}" data-id="${esc(item.id)}"`,'primary full')}${button(`${icon('star')} ${saved?'已保存到我的资源':'保存到我的资源'}`,`data-action="${saved?'removeSaved':'save'}" data-id="${esc(item.id)}" aria-pressed="${saved}"`,'secondary full')}${installed?button('移除演示状态',`data-action="uninstall" data-id="${esc(item.id)}"`,'ghost full'):''}<dl><dt>资源类型</dt><dd>${esc(item.type)}</dd><dt>版本</dt><dd>${esc(item.version)}</dd><dt>来源</dt><dd>${esc(item.source)}</dd><dt>使用范围</dt><dd>当前体验身份</dd></dl>${safeLink(item.url)}<p class="fine-print">本机原型没有连接 DSH；不会下载插件、启动服务或发送任务。</p></aside></div>`;
}

export function libraryView(state) {
  const saved = state.saved[state.actor].map(item=>({...item,savedCopy:true}));
  const installed = catalog(state).filter(item=>isInstalled(state,item.id)&&!saved.some(entry=>entry.id===item.id));
  const items = [...saved,...installed];
  return `<div class="page-heading compact"><div class="eyebrow">YOUR COLLECTION</div><h1>我的资源</h1><p>保存好方法，管理已经添加的能力。</p></div>${items.length?`<div class="resource-grid">${items.map(item=>card(item,state)).join('')}</div>`:empty('给你的工作台添一份能力','在发现页保存感兴趣的资源，或体验添加流程。','<a class="button primary" href="#/discover">去发现资源</a>')}<p class="catalog-note">保存的内容副本会保留；作者发布新版后，由你决定是否更新。</p>`;
}

export function shareView(state, ui) {
  const existing = state.publications.find(item=>item.id===(ui.id||state.drafts[state.actor]?.id));
  if (existing && existing.owner!==state.actor) return empty('当前身份无权编辑','切换至原作者身份后，再维护这份资源。');
  const value = ui.editor || existing || state.drafts[state.actor] || {type:'Prompt',title:'',summary:'',body:'',url:'',version:'0.1.0'};
  return `<div class="page-heading compact"><div class="eyebrow">SHARE SOMETHING USEFUL</div><h1>${existing?'更新你的资源':'让好方法，被更多人发现'}</h1><p>写清用途，给一个示例。你的经验可能正好帮到别人。</p></div><div class="editor-layout"><form id="share-form" class="editor-form" data-id="${esc(existing?.id||'')}"><div class="form-section-title"><span>01</span><h2>告诉大家，这是什么</h2></div><label class="field"><span>资源类型</span><select id="resource-type" name="type" ${existing?'disabled':''}>${TYPES.map(type=>`<option ${value.type===type?'selected':''}>${type}</option>`).join('')}</select></label>${field('资源名称','title',value.title,{required:true,placeholder:'例如：把零散记录整理成周报',extra:'maxlength="80"'})}${field('一句话介绍用途','summary',value.summary,{required:true,multiline:true,placeholder:'它能帮谁，解决什么问题？',extra:'maxlength="300" class="short-textarea"'})}<div class="form-section-title"><span>02</span><h2>${value.type==='Prompt'?'分享你的提示词':'提供内容与发布来源'}</h2></div>${field(value.type==='Prompt'?'提示词内容':'使用说明与依赖','body',value.body,{multiline:true,required:value.type==='Prompt',placeholder:value.type==='Prompt'?'可以用 {{待填内容}} 标记需要使用者填写的位置。':'说明如何使用，需要哪些配置或依赖。',extra:'class="code-editor" maxlength="50000"'})}<div class="upload-row"><label class="button secondary file-button">${icon('upload')} 导入文本文件<input id="resource-file" type="file" accept=".txt,.md,.json" aria-label="导入文本文件"></label><span>支持 TXT、Markdown、JSON，最大 100 KB</span></div>${value.type!=='Prompt'?field('HTTPS 发布地址','url',value.url,{required:true,placeholder:'https://github.com/作者/资源'}):`<details><summary>补充原始来源（可选）</summary>${field('HTTPS 来源地址','url',value.url,{placeholder:'https://…'})}</details>`}${field('版本号','version',value.version,{required:true,placeholder:'0.1.0'})}<p id="form-error" class="inline-error" role="alert"></p><div class="form-actions">${button('保存草稿','type="button" data-action="saveDraft"')}${button(existing?'发布新版本':'发布资源','type="submit"','primary')}</div><p class="fine-print">本机演示发布：只保存在此浏览器，不会上传到真实社区。</p></form><aside class="publish-preview"><div class="preview-label">详情预览 <span>随填写更新</span></div><div id="live-preview">${sharePreview(value)}</div><div class="editor-tip">${icon('leaf')}<h3>一份好分享，从清楚开始</h3><p>说明适用场景和必要条件，给使用者一个容易理解的起点。</p><p>请分享你有权发布的内容，保持作者与来源信息完整。</p></div></aside></div>`;
}
export function sharePreview(value) { return `<span class="resource-icon ${typeClass(value.type)}">${icon(({Prompt:'text',Skill:'spark',MCP:'link',Slash:'slash',插件:'box'})[value.type])}</span>${badge(value.type)}<h2>${esc(value.title||'你的资源名称')}</h2><p>${esc(value.summary||'这里会展示你写下的用途介绍。')}</p><pre>${esc((value.body||'内容预览会出现在这里。').slice(0,650))}</pre><small>版本 ${esc(value.version||'待填写')}</small>`; }

export function publicationsView(state) {
  const items = state.publications.filter(item=>item.owner===state.actor);
  return `<div class="page-heading compact"><div class="eyebrow">MADE BY YOU</div><h1>我的发布</h1><p>让分享持续变好，管理属于你的资源与版本。</p></div>${state.drafts[state.actor]?`<div class="notice">${icon('text')}<span>有一份尚未发布的草稿</span><a href="#/share">继续编辑 ${icon('arrow')}</a></div>`:''}${items.length?`<div class="publication-list">${items.map(item=>`<article class="publication-row"><span class="resource-icon ${typeClass(item.type)}">${icon(item.icon)}</span><div><h2>${esc(item.title)}</h2><p>${esc(item.type)} · ${esc(item.version)} · ${(state.feedback[item.id]||[]).length} 条反馈</p></div>${badge(item.status==='published'?'本机已发布':'已撤回',item.status==='published'?'success':'')}<div class="row-actions"><a class="button secondary" href="#/share/${encodeURIComponent(item.id)}">编辑新版</a>${item.status==='published'?`<a class="button ghost" href="#/resource/${encodeURIComponent(item.id)}">查看</a>${button('撤回',`data-action="withdraw" data-id="${esc(item.id)}"`,'ghost')}`:''}</div></article>`).join('')}</div>`:empty('你的第一份分享，从这里开始','提示词、工具或技能，都可以成为社区的新收获。','<a class="button primary" href="#/share">分享资源</a>')}`;
}

export function sourcesView(state, ui) {
  const source = state.source;
  return `<div class="page-heading compact"><div class="eyebrow">CONNECTED SOURCES</div><h1>资源来源</h1><p>社区分享与外部来源，一起丰富你的选择。</p></div><div class="source-list"><article class="source-row"><span class="resource-icon prompt">${icon('leaf')}</span><div><h2>本机演示社区</h2><p>展示你和另一个体验身份发布的资源。</p></div>${badge(`${state.publications.filter(item=>item.status==='published').length} 份已发布`,'success')}</article><article class="source-row"><span class="resource-icon skill">${icon('spark')}</span><div><h2>Anthropic Skills</h2><p>从作者公开仓库读取真实目录，确认 internal-comms 样本仍存在。</p><p class="source-detail">${source.checkedAt?`上次成功：${esc(new Date(source.checkedAt).toLocaleString('zh-CN'))} · 返回 ${source.count} 个目录${source.sampleFound?' · 样本存在':' · 未找到样本'}`:'尚未获得成功读取记录'}</p>${source.error?`<p class="inline-error">${esc(source.error)}。已有来源样本与上次信息仍保留。</p>`:''}</div>${button(`${icon('refresh')} ${ui.syncing?'读取中…':'刷新来源'}`,'data-action="refreshSource" '+(ui.syncing?'disabled':''))}</article><article class="source-row"><span class="resource-icon mcp">${icon('link')}</span><div><h2>MCP Registry / DSH 发布源</h2><p>当前卡片来自已查阅的来源样本；持续目录同步尚未接入。</p></div>${badge('待接入')}</article></div><div class="info-block"><h2>这里的状态意味着什么？</h2><p>目录读取是实际网络请求。本轮只验证一个来源的目录与样本存在性，不会下载 Skill，也没有完成全量资源同步。</p><p>投稿和私有内容留在本机，来源请求不携带你的任务草稿。</p></div>`;
}

export function updatesView(state) {
  const updates = state.saved[state.actor].map(copy=>({copy,latest:catalog(state).find(item=>item.id===copy.id)})).filter(({copy,latest})=>latest&&copy.version!==latest.version);
  const history = state.history[state.actor];
  return `<div class="page-heading compact"><div class="eyebrow">KEEP YOUR WORK IN YOUR HANDS</div><h1>更新与恢复</h1><p>了解变化，再决定下一步。</p></div><h2 class="section-title">资源版本</h2>${updates.length?updates.map(({copy,latest})=>`<div class="publication-row"><span class="resource-icon ${typeClass(copy.type)}">${icon(copy.icon)}</span><div><h2>${esc(copy.title)}</h2><p>${esc(copy.version)} → ${esc(latest.version)} · 本机保存的副本仍是原版</p></div>${button('查看并更新',`data-action="updateSaved" data-id="${esc(copy.id)}"`)}</div>`).join(''):empty('已保存的资源暂时没有更新','作者发布新版本后，会在这里提示。')}<h2 class="section-title">最近的演示操作</h2>${history.length?`<div class="notice">${icon('clock')}<span>${esc(history.at(-1).label)}<small>只恢复本机原型的安装状态，不涉及真实文件或 DSH 环境。</small></span>${button('恢复上一步','data-action="restore"')}</div>`:empty('还没有需要恢复的演示操作','体验添加或移除资源后，可以在这里检查恢复流程。')}`;
}

export function taskView(state) {
  return `<div class="page-heading compact"><div class="eyebrow">READY WHEN YOU ARE</div><h1>任务草稿</h1><p>先检查内容，再交给你的 Agent。</p></div><div class="task-layout"><div class="task-editor"><div class="section-head"><h2>当前草稿</h2>${badge('本机自动保存')}</div>${field('准备发送的内容','task-draft',state.tasks[state.actor],{multiline:true,placeholder:'使用一个 Prompt 后，填写好的内容会追加到这里。',extra:'class="task-textarea"'})}<div class="form-actions">${button('复制草稿','data-action="copyTask"')}${button('预览发送流程','data-action="sendPreview"','primary')}</div><p class="fine-print">尚未连接 DSH 或模型。可复制内容自行使用；这里不会发送任何请求。</p></div><aside class="task-note">${icon('text')}<h2>每一次发送，都由你决定</h2><p>从资源详情使用提示词，填写变量后查看完整预览。</p><p>新的内容会追加到草稿，保留你已经写下的记录。</p><a class="text-link" href="#/resource/weekly-prompt">试用周报模板 ${icon('arrow')}</a></aside></div>`;
}
